### ISSUE TITLE
Feature Request: Lazy Loading

### ISSUE THREAD

**Issue by kyeotic** [keroxp/dino#1]
It would be super handy if the `.set()` took a function that returned the value so that we could delay the construction of slow modules until they were requested

**Comment by keroxp** [comment]
@kyeotic 

How about setting provider function to the registry?

```ts
const di = new DI<{
  promiseValue: () => Promise<number>
}>()
di.set("promiseValue", async () => 1)
const value = await di.get("promiseValue")()
```

**Comment by kyeotic** [comment]
An async would be cool but a sync would be more useful for my use cases. I'm just trying to ensure some `require` calls are avoided if possible, as they incur parsing time. 

Offering both probably wouldn't add much weight.

**Comment by keroxp** [comment]
@kyeotic Do you talk about like this?

```ts
const di = new DI<{
  service: Service,
}>()
di.setLazy("service", () => {
  const Service = require("./service");
  return new Service();
})
const s1 = di.get("service")
const s2 = di.get("service")
// s1 === s2
```

**Comment by kyeotic** [comment]
Nailed it

**Comment by keroxp** [comment]
Yeah, certainly it would be nice.

**Comment by keroxp** [comment]
@kyeotic Done in v2. Have fun🦕
